"""AI Sales Team — full B2B sales pod powered by AWS Strands agents."""

from .models import (
    CareerRole,
    ClosingStrategy,
    DealOutcome,
    DealResult,
    DecisionMakerSignal,
    DeepResearchRequest,
    DeepResearchResult,
    DiscoveryPlan,
    IdealCustomerProfile,
    LearningInsights,
    NurtureSequence,
    OutreachSequence,
    PipelineStage,
    Prospect,
    ProspectDossier,
    ProspectListEntry,
    PublicWorkItem,
    QualificationScore,
    SalesPipelineRequest,
    SalesPipelineResult,
    SalesProposal,
    StageOutcome,
)
from .orchestrator import SalesPodOrchestrator

__all__ = [
    "SalesPodOrchestrator",
    "SalesPipelineRequest",
    "SalesPipelineResult",
    "PipelineStage",
    "IdealCustomerProfile",
    "Prospect",
    "OutreachSequence",
    "QualificationScore",
    "NurtureSequence",
    "DiscoveryPlan",
    "SalesProposal",
    "ClosingStrategy",
    "StageOutcome",
    "DealOutcome",
    "DealResult",
    "LearningInsights",
    # Deep-research prospecting
    "DeepResearchRequest",
    "DeepResearchResult",
    "ProspectListEntry",
    "ProspectDossier",
    "CareerRole",
    "PublicWorkItem",
    "DecisionMakerSignal",
]
