"""Temporal workflow + activity wrapping the market research orchestrator.

Generated by the shared_temporal migration: every team exposes a single
``{Team}Workflow`` that invokes one activity wrapping its existing
orchestrator entrypoint. Agent logic is unchanged; Temporal just owns
durable execution, retries, and checkpoint-based resume.
"""

from __future__ import annotations

from datetime import timedelta
from typing import Any

from temporalio import activity, workflow


@activity.defn(name="market_research_run_pipeline")
def run_pipeline_activity(request: dict[str, Any]) -> dict[str, Any]:
    from market_research_team.api.main import RunMarketResearchRequest
    from market_research_team.orchestrator import MarketResearchOrchestrator

    req = RunMarketResearchRequest(**request)
    result = MarketResearchOrchestrator().run(req)
    if hasattr(result, "model_dump"):
        return result.model_dump()
    return result if isinstance(result, dict) else {"result": result}


@workflow.defn(name="MarketResearchWorkflow")
class MarketResearchWorkflow:
    @workflow.run
    async def run(self, request: dict[str, Any]) -> dict[str, Any]:
        return await workflow.execute_activity(
            run_pipeline_activity,
            request,
            start_to_close_timeout=timedelta(hours=2),
        )


WORKFLOWS = [MarketResearchWorkflow]
ACTIVITIES = [run_pipeline_activity]

from shared_temporal import is_temporal_enabled, start_team_worker  # noqa: E402

if is_temporal_enabled():
    start_team_worker(
        "market_research", WORKFLOWS, ACTIVITIES, task_queue="market_research-queue"
    )
