"""Temporal workflow + activity wrapping the market research orchestrator.

Generated by the shared_temporal migration: every team exposes a single
``{Team}Workflow`` that invokes one activity wrapping its existing
orchestrator entrypoint. Agent logic is unchanged; Temporal just owns
durable execution, retries, and checkpoint-based resume.
"""

from __future__ import annotations

from datetime import timedelta
from typing import Any

from temporalio import activity, workflow


@activity.defn(name="market_research_run_pipeline")
def run_pipeline_activity(request: dict[str, Any]) -> dict[str, Any]:
    from market_research_team.api.main import RunMarketResearchRequest
    from market_research_team.models import HumanReview, ResearchMission
    from market_research_team.orchestrator import MarketResearchOrchestrator

    req = RunMarketResearchRequest(**request)
    mission = ResearchMission(
        product_concept=req.product_concept,
        target_users=req.target_users,
        business_goal=req.business_goal,
        topology=req.topology,
        transcript_folder_path=req.transcript_folder_path,
        transcripts=req.transcripts,
    )
    human_review = HumanReview(approved=req.human_approved, feedback=req.human_feedback)
    result = MarketResearchOrchestrator().run(mission, human_review)
    if hasattr(result, "model_dump"):
        return result.model_dump()
    return result if isinstance(result, dict) else {"result": result}


@workflow.defn(name="MarketResearchWorkflow")
class MarketResearchWorkflow:
    @workflow.run
    async def run(self, request: dict[str, Any]) -> dict[str, Any]:
        return await workflow.execute_activity(
            run_pipeline_activity,
            request,
            start_to_close_timeout=timedelta(hours=2),
        )


WORKFLOWS = [MarketResearchWorkflow]
ACTIVITIES = [run_pipeline_activity]

from shared_temporal import is_temporal_enabled, start_team_worker  # noqa: E402

if is_temporal_enabled():
    start_team_worker("market_research", WORKFLOWS, ACTIVITIES, task_queue="market_research-queue")
